default_language_version:
  # default language version for each language
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--django"]
      - id: trailing-whitespace

  # See Documentation https://flake8.pycqa.org/en/latest/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
  #  See documentation https://pylint.pycqa.org/en/latest/
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: "[a-zA-Z]*/(migrations)/(.)*|[a-zA-Z]*/(.venv)/(.)*"
        args: ["--rcfile=.pylintrc"]

  # See documentation https://black.readthedocs.io/en/stable/
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
        types: [python]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.971
  #   hooks:
  #     - id: mypy
  #       args: [--no-strict-optional, --ignore-missing-imports]
  #       additional_dependencies: ["types-requests"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
